name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-changelog-md:
    name: Generate changeloge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bump version and update CHANGELOG.MD
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.11.0
        with:
          git-message: "chore(release): {version}"
          tag-prefix: ""
          output-file: "CHANGELOG.md"
          release-count: 10 # save all releases in the CHANGELOG.md
          git-push: false
