name: CI

on:
  pull_request:
    branches:
      - main
      - release/*
      - hotfix/*
      - major/*
      - chore/*

jobs:
  create-changelog:
    - name: Conventional Changelog Action
    uses: TriPSs/conventional-changelog-action@v3
